In [1]:
import numpy as np

In [2]:
np.array(10)#scaler or 0-d array

array(10)

In [4]:
arr1=np.array([1,2,3,4]) #1-d array
print(arr1)

[1 2 3 4]


In [6]:
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
arr1.shape

(4,)

In [8]:
arr2=np.array([[1,2,3],[5,6,7]])

In [9]:
print(arr2)

[[1 2 3]
 [5 6 7]]


In [10]:
print(arr2.shape)

(2, 3)


In [11]:
print(arr2.ndim) # ndim provide the dimension of an array


2


In [12]:
a=np.array(10)
print(a)
print(a.shape)
print(a.ndim)
print(type(a))

10
()
0
<class 'numpy.ndarray'>


In [14]:
b= np.array([1,2,3,4])
print(b)
print(b.ndim)
print(b.shape)
print(type(b))

[1 2 3 4]
1
(4,)
<class 'numpy.ndarray'>


In [15]:
c=np.array([[1,2,3],[5,4,6]])
print(c)
print(c.ndim)
print(c.shape )
print(type(c))

[[1 2 3]
 [5 4 6]]
2
(2, 3)
<class 'numpy.ndarray'>


In [17]:
d=np.array([1,2,34,5],ndmin=2)
print(d)
print(d.shape)
print(d.ndim)

[[ 1  2 34  5]]
(1, 4)
2


In [18]:
e=np.array(3,ndmin=5)
print(e)
print(e.ndim)

[[[[[3]]]]]
5


In [20]:
f=np.array([1,2,3],ndmin=5)
print(f)

[[[[[1 2 3]]]]]


In [21]:
np.zeros(1)

array([0.])

In [23]:
np.zeros(2)

array([0., 0.])

In [30]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
a=np.zeros(2)
print(a)
print(a.ndim)

[0. 0.]
1


In [55]:
b=np.zeros((4,3))
print(b)
print(b.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [29]:
np.zeros((2,2,2,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [57]:
np.arange(10) # this belong to numpy return an iterable and it value inside an array   

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
range(10) #this belongs to python only return iterable

range(0, 10)

1>range()
It comes as a default function of Python.
It is independent of any library or module.
This comes as a built-in default function with the Python interpreter.
2> arange()
It comes under the NumPy library of Python.
It depends on the NumPy library. Without importing the NumPy, you will not be able to use it.
This comes as a third-party module-based function.



In [59]:
np.arange(0,10)   # start value_will be 0 bydefault,end value(exclusive), step(bydefault 1)  


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(0,10,1)  # start value, end value, step

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [62]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [71]:
np.array([i for i in range(100)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [72]:
b=np.array(a)

In [73]:
import sys

In [74]:
sys.getsizeof(a) # list use higher value as compare to array with same number of elments, hence it faster


128

In [75]:
sys.getsizeof(b)

128

In [76]:
# precedence
# array: a collection which contain similar datatype called array.it never allows hetrogenous(dis similar datatype) datatype

In [77]:
np.array([1,2.33,'kalraj'])

array(['1', '2.33', 'kalraj'], dtype='<U32')

In [81]:
np.array([1,1.34,'kalraj'],dtype=np.int128)

AttributeError: module 'numpy' has no attribute 'int128'

In [82]:
np.array([1,1.34,'kalraj'],dtype=np.int64)


ValueError: invalid literal for int() with base 10: 'kalraj'

In [84]:
a=np.array([1,2.343,"10",'89'],dtype=np.int8)
print(a)
sys.getsizeof(a)

[ 1  2 10 89]


116

In [86]:
b=np.array([1,2.343,"10",'89'],dtype=np.int64)
print(b)
sys.getsizeof(b)

[ 1  2 10 89]


144

In [88]:
c=np.array([1,2,3.78],dtype=np.float64)

In [89]:
print(c)

[1.   2.   3.78]


In [90]:
d=np.array([1,2.343,"10.0"],dtype=np.float32)
print(d)

[ 1.     2.343 10.   ]


In [93]:
e=np.array(np.array([1,2.343,"10.0"],dtype=np.float32))

In [94]:
print(e)

[ 1.     2.343 10.   ]


In [95]:
e=np.array(np.array([1,2.343,"10.0"],dtype=np.float32),dtype=np.int8)


In [96]:
print(e)

[ 1  2 10]


In [97]:
np.array(e,dtype=np.str_)

array(['1', '2', '10'], dtype='<U4')

In [99]:
np.ones(2)

array([1., 1.])

In [101]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [104]:
np.ones((2,3,10))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [108]:
np.full((10,),2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [110]:
np.linspace(1,100,4)#start, end,size  (start and end both are inclusive)

array([  1.,  34.,  67., 100.])

In [112]:
np.random.randint(1,7,(3,2,10))# start,end(exclusive),matrix size(tuple)

array([[[2, 2, 5, 3, 6, 1, 3, 5, 3, 6],
        [6, 6, 5, 6, 1, 2, 4, 1, 6, 4]],

       [[4, 2, 4, 5, 2, 6, 4, 6, 2, 4],
        [1, 2, 3, 1, 3, 4, 2, 5, 3, 6]],

       [[1, 3, 1, 6, 5, 2, 4, 2, 2, 5],
        [2, 5, 5, 6, 5, 5, 2, 2, 6, 1]]])

In [113]:
#copy
a=np.array([1,2,3,4,5])

In [114]:
print(a)

[1 2 3 4 5]


In [115]:
c=a.copy()

In [116]:
print(c)

[1 2 3 4 5]


In [117]:
a[0]=10
c[1]=20

In [118]:
print(a)
print(c)

[10  2  3  4  5]
[ 1 20  3  4  5]


In [121]:
#view
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [122]:
d=a.view()

In [123]:
print(d)

[1 2 3 4 5 6]


In [124]:
a[0]=100
d[1]=20

In [125]:
print(a)
print(d)

[100  20   3   4   5   6]
[100  20   3   4   5   6]


In [126]:
# joining array by concatenate()method
a=np.array([1,2,3,4])
b=np.array([6,4,7,3,7])

In [127]:
print(a)
print(b)

[1 2 3 4]
[6 4 7 3 7]


In [129]:
c=np.concatenate((a,b))

In [130]:
print(c)

[1 2 3 4 6 4 7 3 7]


In [131]:
d=np.array([[1,2,3],[4,3,2]])
e=np.array([1,2,3])

In [133]:
f=np.concatenate((d,e))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [140]:
d=np.array([[1,2,3],[4,3,2]])
e=np.array([[1,2,3],[15,46,23]])

In [141]:
f=np.concatenate((d,e))

In [142]:
print(f)

[[ 1  2  3]
 [ 4  3  2]
 [ 1  2  3]
 [15 46 23]]


In [149]:
a=np.array([i for i in range(20)])
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [153]:
b=np.array_split(a,2)

In [154]:
print(b)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]


In [155]:
c,d=b

In [156]:
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [161]:
e=np.array(np.arange(1,10))

In [162]:
print(e)

[1 2 3 4 5 6 7 8 9]


In [167]:
f=np.array_split(e,4)

In [169]:
a,b,c,d=f

In [171]:
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[4 5]
[6 7]
[8 9]


In [172]:
arr=np.array([[1,2,3,4],[4,5,6,7]])

In [173]:
print(arr)

[[1 2 3 4]
 [4 5 6 7]]


In [174]:
d=np.hsplit(arr,2)

In [176]:
a,b=d
print(a)
print(b)

[[1 2]
 [4 5]]
[[3 4]
 [6 7]]


In [187]:
print(arr)
f=np.vsplit(arr,2)


[[1 2 3 4]
 [4 5 6 7]]


In [186]:
print(f)

[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]])]


In [197]:
#searching array element
arr2=np.array([1,2,3,4,2,5])
p=np.where(arr2==2)
print(p)

(array([1, 4], dtype=int64),)


In [199]:
arr3=np.array([1,2,4,5,2,5,1,6,2,8,2])
x=np.searchsorted(arr3,4,side="Right")
print(x)

5


In [245]:
a=np.array([1,2,-3,4,-5,0,6,8,-6,5])
count_positive_number=0
count_negative_number=0
count_number=0
print(len(a))
for i in range(len(a)):
    if a[i]>0:
        count_positive_number+=1
        
    elif a[i]<0:
        count_negative_number+=1
    
    else:
        count_number+=1  
print("%1.6"%(count_positive_number/len(a)))
print(count_negative_number/len(a))
print(count_number/len(a))
          
print(count_number)
print(count_negative_number)
print(count_positive_number)     

10
0.6
0.3
0.1
1
3
6


In [267]:
a=[1,2,3,4,5]
cont=[]
i=0

while(i<len(a)):
    sum=0
    for j in range(i,len(a)):
        sum=sum+a[j]
    i=i+1
    cont.append(sum)
print(max(cont))
print(min(cont))

[15, 14, 12, 9, 5]
