In [12]:
import numpy as np

In [18]:
arr=np.array(np.random.randint(1,10,(2,3)))
arr

array([[5, 1, 5],
       [6, 6, 1]])

In [20]:
print('hello'+1+2+3)

TypeError: can only concatenate str (not "int") to str

In [21]:
import numpy as geek
  
a = geek.full([2, 2], 67, dtype = int)
print("\nMatrix a : \n", a)
  
c = geek.full([3, 3], 10.1)
print("\nMatrix c : \n", c)


Matrix a : 
 [[67 67]
 [67 67]]

Matrix c : 
 [[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


In [24]:
import datetime as dt


In [26]:
dt.datetime.now()

datetime.datetime(2023, 6, 4, 18, 26, 44, 817774)

In [29]:
x=dt.datetime.now()
print(x.strftime("%X%p"))
    

18:31:37PM


from datetime import datetime
 
def convert24(time):
    # Parse the time string into a datetime object
    t = datetime.strptime(time, '%I:%M:%S %p')
    # Format the datetime object into a 24-hour time string
    return t.strftime('%H:%M:%S')
 
print(convert24('11:21:30 PM'))

In [33]:
from datetime import datetime
 
def convert24(time):
    # Parse the time string into a datetime object
    t = datetime.strptime(time, '%I:%M:%S %p')
    # Format the datetime object into a 24-hour time string
    return t.strftime('%H:%M:%S')
 
print(convert24('11:21:30 PM'))

23:21:30


In [125]:
a=[1,2,3,4,2,8,1,4,3,4,7,7]
for i in range(len(a)):
    c=0
    for j in range(len(a)):
        if a[i]==a[j]:
            c=c+1
    if c==1:
        print(a[i])
        
            
            

8


In [126]:
import numpy as np

In [128]:
matrics=np.array([[1,2,3],[4,5,6],[9,8,9]])
matrics

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 9]])

In [129]:
sum_daigonal=0
for i in range(len(matrics)):
    for j in range(len(matrics)):
        if i==j:
            sum_daigonal=sum_daigonal+matrics[i][j]
print(sum_daigonal)
        

[1 2 3]
[4 5 6]
[9 8 9]
